"""
Django settings for DE 2016 project.

Generated by 'django-admin startproject' using Django 1.8.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=8(l!cebjf5e5saw+r@3yx@wjhi(8#mrqfi(l6ezy$*5w1$++mL3tsseeifRvrSpotsth7s0n3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    ## oAuth
    # 'oauth2_provider',
    # 'corsheaders',


    'oauth_tokens',
    'm2m_history',
    'taggit',
    'twitter_api',
    #
    #
    'website',
    'django_instagram',

)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'


## CREATE a twitter account we can use, then create an app here: https://apps.twitter.com/app/new

## Twitter settings
# oauth-tokens settings
OAUTH_TOKENS_HISTORY = True                                        # to keep in DB expired access tokens
OAUTH_TOKENS_TWITTER_CLIENT_ID = ''                                # application ID
OAUTH_TOKENS_TWITTER_CLIENT_SECRET = ''
OAUTH_TOKENS_TWITTER_USERNAME = ''                                 # user login
OAUTH_TOKENS_TWITTER_PASSWORD = ''                                 # user password

OAUTH_TOKENS_TWITTER_REDIRECT_URI = 'bka'   # not used, but NEEDED!

## fabrique developers twitter account app
OAUTH_TOKENS_TWITTER_CLIENT_ID = '8Q4vNnxrbfhqeQpLmDwKawQPt'
OAUTH_TOKENS_TWITTER_CLIENT_SECRET = 'Jad7o1vDTyv85O6vnK2MuBHkLd6bJhzY0t4wtZniSH3x7geggW'
# OAUTH_TOKENS_TWITTER_USERNAME = 'fabriquedevs'
OAUTH_TOKENS_TWITTER_USERNAME = 'fabrique.developers@gmail.com'
OAUTH_TOKENS_TWITTER_PASSWORD = 'X=+L5K|_u8kT'

import dj_database_url
DATABASES['default'] = dj_database_url.config()

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ALLOWED_HOSTS = ['*']

DEBUG = False

try:
    from .local_settings import *
except ImportError:
    pass
